import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '..');
const dist = path.join(root, 'dist');
const built = fs.existsSync(path.join(dist, 'rss.xml'));

test('default Hagilight and Starlight Blog RSS feeds are generated by their integrations', { skip: !built }, async () => {
  const [docsFeed, blogFeed, config] = await Promise.all([
    fs.promises.readFile(path.join(dist, 'rss.xml'), 'utf8'),
    fs.promises.readFile(path.join(dist, 'blog/rss.xml'), 'utf8'),
    fs.promises.readFile(path.join(root, 'astro.config.mjs'), 'utf8'),
  ]);

  assert.match(docsFeed, /^<\?xml/u);
  assert.match(docsFeed, /<rss\b/u);
  assert.match(blogFeed, /^<\?xml/u);
  assert.match(blogFeed, /<rss\b/u);
  assert.match(config, /starlightBlog\(\)/u);
  assert.doesNotMatch(config, /rss:\s*\{|hagilightRss|rss-feed/u);
  assert.equal(fs.existsSync(path.join(root, 'src/lib/blog-rss.ts')), false);
});
