import type { DocsLocale } from '@/lib/i18n';

type SidebarTranslations = Partial<Record<Exclude<DocsLocale, 'root'>, string>>;

function createTranslations(translations: SidebarTranslations): SidebarTranslations {
  return translations;
}

export const DOCS_SIDEBAR = [
  {
    label: '产品概述',
    translations: createTranslations({
      'en-US': 'Product Overview',
      'zh-Hant': '產品概覽',
      'ja-JP': '製品概要',
      'ko-KR': '제품 개요',
      'de-DE': 'Produktübersicht',
      'fr-FR': 'Vue d’ensemble du produit',
      'es-ES': 'Descripción general del producto',
      'pt-BR': 'Visão geral do produto',
      'ru-RU': 'Обзор продукта',
    }),
    link: '/product-overview',
  },
  {
    label: '快速开始',
    translations: createTranslations({
      'en-US': 'Quick Start',
      'zh-Hant': '快速開始',
      'ja-JP': 'クイックスタート',
      'ko-KR': '빠른 시작',
      'de-DE': 'Schnellstart',
      'fr-FR': 'Démarrage rapide',
      'es-ES': 'Inicio rápido',
      'pt-BR': 'Início rápido',
      'ru-RU': 'Быстрый старт',
    }),
    autogenerate: { directory: 'quick-start' },
  },
  {
    label: '安装指南',
    translations: createTranslations({
      'en-US': 'Installation Guide',
      'zh-Hant': '安裝指南',
      'ja-JP': 'インストールガイド',
      'ko-KR': '설치 가이드',
      'de-DE': 'Installationsanleitung',
      'fr-FR': 'Guide d’installation',
      'es-ES': 'Guía de instalación',
      'pt-BR': 'Guia de instalação',
      'ru-RU': 'Руководство по установке',
    }),
    autogenerate: { directory: 'installation' },
  },
  {
    label: '常见问题',
    translations: createTranslations({
      'en-US': 'FAQ',
      'zh-Hant': '常見問題',
      'ja-JP': 'よくある質問',
      'ko-KR': '자주 묻는 질문',
      'de-DE': 'Häufige Fragen',
      'fr-FR': 'FAQ',
      'es-ES': 'Preguntas frecuentes',
      'pt-BR': 'Perguntas frequentes',
      'ru-RU': 'Часто задаваемые вопросы',
    }),
    autogenerate: { directory: 'faq' },
  },
  {
    label: '相关软件安装',
    translations: createTranslations({
      'en-US': 'Related Software Installation',
      'zh-Hant': '相關軟體安裝',
      'ja-JP': '関連ソフトウェアのインストール',
      'ko-KR': '관련 소프트웨어 설치',
      'de-DE': 'Installation verwandter Software',
      'fr-FR': 'Installation des logiciels associés',
      'es-ES': 'Instalación de software relacionado',
      'pt-BR': 'Instalação de software relacionado',
      'ru-RU': 'Установка связанного ПО',
    }),
    autogenerate: { directory: 'related-software-installation' },
  },
  {
    label: '功能指南',
    translations: createTranslations({
      'en-US': 'Guides',
      'zh-Hant': '功能指南',
      'ja-JP': 'ガイド',
      'ko-KR': '가이드',
      'de-DE': 'Anleitungen',
      'fr-FR': 'Guides',
      'es-ES': 'Guías',
      'pt-BR': 'Guias',
      'ru-RU': 'Руководства',
    }),
    autogenerate: { directory: 'guides' },
  },
  {
    label: '大模型指南',
    translations: createTranslations({
      'en-US': 'LLM Guide',
      'zh-Hant': '大模型指南',
      'ja-JP': 'LLM ガイド',
      'ko-KR': 'LLM 가이드',
      'de-DE': 'LLM-Leitfaden',
      'fr-FR': 'Guide LLM',
      'es-ES': 'Guía de LLM',
      'pt-BR': 'Guia de LLM',
      'ru-RU': 'Руководство по LLM',
    }),
    autogenerate: { directory: 'llm-guide' },
  },
  {
    label: 'AI 服务订阅网站',
    translations: createTranslations({
      'en-US': 'AI Service Subscriptions',
      'zh-Hant': 'AI 服務訂閱網站',
      'ja-JP': 'AI サービス購読サイト',
      'ko-KR': 'AI 서비스 구독 사이트',
      'de-DE': 'KI-Dienst-Abonnements',
      'fr-FR': 'Abonnements de services IA',
      'es-ES': 'Suscripciones de servicios de IA',
      'pt-BR': 'Assinaturas de serviços de IA',
      'ru-RU': 'Подписки на AI-сервисы',
    }),
    autogenerate: { directory: 'ai-service-subscriptions' },
  },
  {
    label: '法律文档',
    translations: createTranslations({
      'en-US': 'Legal',
      'zh-Hant': '法律文件',
      'ja-JP': '法的文書',
      'ko-KR': '법률 문서',
      'de-DE': 'Rechtliches',
      'fr-FR': 'Documents juridiques',
      'es-ES': 'Documentos legales',
      'pt-BR': 'Documentos legais',
      'ru-RU': 'Юридические документы',
    }),
    autogenerate: { directory: 'legal' },
  },
  {
    label: '版本更新说明',
    translations: createTranslations({
      'en-US': 'Release Notes',
      'zh-Hant': '版本更新說明',
      'ja-JP': 'リリースノート',
      'ko-KR': '릴리스 노트',
      'de-DE': 'Versionshinweise',
      'fr-FR': 'Notes de version',
      'es-ES': 'Notas de la versión',
      'pt-BR': 'Notas de versão',
      'ru-RU': 'Примечания к выпуску',
    }),
    link: '/release-notes',
  },
  {
    label: 'DLC',
    translations: createTranslations({
      'en-US': 'DLC',
      'zh-Hant': 'DLC',
      'ja-JP': 'DLC',
      'ko-KR': 'DLC',
      'de-DE': 'DLC',
      'fr-FR': 'DLC',
      'es-ES': 'DLC',
      'pt-BR': 'DLC',
      'ru-RU': 'DLC',
    }),
    autogenerate: { directory: 'dlc' },
  },
  {
    label: 'Bundles',
    translations: createTranslations({
      'en-US': 'Bundles',
      'zh-Hant': '套件組合',
      'ja-JP': 'バンドル',
      'ko-KR': '번들',
      'de-DE': 'Bundles',
      'fr-FR': 'Packs',
      'es-ES': 'Paquetes',
      'pt-BR': 'Pacotes',
      'ru-RU': 'Наборы',
    }),
    autogenerate: { directory: 'bundles' },
  },
];
